title: Hypatia
description: Formal-System Assistant Toolkit
url: "https://hypatiafsa.github.io"

exclude:
  - .editorconfig
  - .gitattributes
  - .gitignore
  - .markdownlint.json
  - Gemfile
  - Gemfile.lock
  - readme.md
  - test.sh

sass:
  style: compressed

branch: dev
repo: https://github.com/hypatiafsa/hypatia
hackage: https://hackage.haskell.org/package/hypatia
stackage: https://www.stackage.org/package/hypatia

vscode_repo: https://github.com/hypatiafsa/vscode
vscode_marketplace: https://marketplace.visualstudio.com/items?itemName=HypatiaFSA.hypatia
vscode_openvsx: https://open-vsx.org/extension/HypatiaFSA/hypatia

header:
  links:
    - label: Architecture
      path: /doc/architecture.md
      kind: blob
    - label: Language
      path: /doc/hypatia.md
      kind: blob
    - label: Formalisation
      path: /hyp
      kind: tree
    - label: Examples
      path: /exm
      kind: tree

footer:
  copyright: "Copyright © 2025-2026, the Hypatia Development Team."
  links:
    - label: Source
      path: /
      kind: tree
    - label: Issues
      path: /issues
      kind: root
    - label: Changelog
      path: /changelog.md
      kind: blob
    - label: Contributors
      path: /contributors.txt
      kind: blob
